"""Methodology & Data Sources reference page — extracted from streamlit_app.py."""

import streamlit as st

from utils.components import (
    render_feedback_widget as _render_feedback_widget,
    render_glossary as _render_glossary,
)
from utils.constants import C


def render():
    """Methodology & data sources reference page — pure static content."""

    st.markdown(
        "<h1 style='margin-bottom:0.1rem;'>📖 Methodology & Data Sources</h1>"
        f"<p style='color:{C.text_dim};font-size:0.82rem;margin-bottom:1.5rem;'>"
        "Every metric, formula, and term used across the MLB Toolbox — explained in one place.</p>",
        unsafe_allow_html=True,
    )

    # ── helper: styled section header ────────────────────────────────────
    def _section(num: int, title: str):
        st.markdown(
            f"<div style='margin:1.8rem 0 0.6rem;padding:0.5rem 0.8rem;"
            f"border-left:3px solid #2b5cc8;background:{C.bg_dark};border-radius:0 8px 8px 0;'>"
            f"<span style='font-size:0.7rem;color:{C.accent_blue};font-weight:700;'>SECTION {num}</span>"
            f"<div style='font-size:1.05rem;font-weight:700;color:{C.text_primary};'>{title}</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

    # ==================================================================
    # Section 1 — Core Baseball Stats
    # ==================================================================
    _section(1, "Core Baseball Stats")

    _render_glossary([
        ("fWAR", "Wins Above Replacement (FanGraphs)",
         "WAR estimates a player's value in terms of extra wins they provide compared to a "
         "replacement-level player — essentially a low-cost minor leaguer or bench player easily "
         "found to fill the same position. MLB Toolbox uses fWAR, a widely accepted version "
         "generated by FanGraphs."),
        ("wRC+", "Weighted Runs Created Plus",
         "Park- and league-adjusted offensive metric. 100 = league average; "
         "150 means 50% better than average."),
        ("FIP", "Fielding Independent Pitching",
         "Estimates a pitcher's ERA based only on events they control: strikeouts, walks, HBP, "
         "and home runs. Lower is better."),
        ("BABIP", "Batting Avg on Balls In Play",
         "Batting average on balls put into play (excludes HR, K, BB). "
         "League average is ~.300; extreme values often regress."),
        ("OPS", "On-base Plus Slugging",
         "Sum of on-base percentage and slugging percentage. Quick offensive snapshot; "
         "league average is around .710-.730."),
        ("OPS+", "Adjusted OPS",
         "Park- and league-normalized OPS. 100 = league average. "
         "Comparable across eras and ballparks."),
        ("ERA", "Earned Run Average",
         "Earned runs allowed per 9 innings pitched. Influenced by defense and luck; "
         "FIP is generally a better skill measure."),
        ("WHIP", "Walks + Hits per Inning Pitched",
         "Baserunners allowed per inning. Sub-1.00 is elite; league average is ~1.25."),
        ("K/9", "Strikeouts per 9 Innings",
         "Strikeout rate normalized to 9 innings. Higher is better for pitchers."),
        ("BB/9", "Walks per 9 Innings",
         "Walk rate normalized to 9 innings. Lower is better for pitchers."),
        ("HR/9", "Home Runs per 9 Innings",
         "Home run rate normalized to 9 innings. Heavily influences FIP and ERA."),
        ("UZR", "Ultimate Zone Rating",
         "Advanced fielding metric measuring runs saved/cost relative to an average "
         "defender at the same position. Measured in runs above average."),
        ("DRS", "Defensive Runs Saved",
         "Fielding metric from Baseball Info Solutions. Positive = above-average defender. "
         "Comparable to UZR but uses a different methodology."),
        ("oWAR", "Offensive WAR",
         "WAR component from batting and baserunning only, excluding defense. "
         "Useful for isolating hitting contribution."),
        ("dWAR", "Defensive WAR",
         "WAR component from fielding only. Combines UZR/DRS-type metrics with "
         "positional adjustment."),
        ("bWAR vs fWAR", "Baseball-Reference WAR vs FanGraphs WAR",
         "bWAR (B-Ref) uses RA/9 for pitchers (actual runs); fWAR (FanGraphs) uses FIP "
         "(fielding-independent). This project uses fWAR exclusively. "
         "FanGraphs WAR (fWAR) is applied given its focus on attempting to predict future "
         "performance and evaluating player talent level."),
    ], title="Core Baseball Stats", cols=2)

    # WAR formula breakdown
    st.markdown(
        "<div style='margin:0.6rem 0 0.2rem;font-size:0.82rem;font-weight:700;color:#93c5fd;'>"
        "Full fWAR Formula Breakdown</div>",
        unsafe_allow_html=True,
    )

    c1, c2 = st.columns(2)
    with c1:
        st.markdown(
            f"<div style='font-size:0.75rem;font-weight:600;color:{C.text_primary};margin-bottom:0.3rem;'>"
            "Position Players</div>",
            unsafe_allow_html=True,
        )
        st.latex(
            r"\text{fWAR} = \frac{"
            r"\text{Bat} + \text{BsR} + \text{Fld} + \text{Pos} + \text{Lg} + \text{Rep}"
            r"}{\text{RPW}}"
        )
        st.caption(
            "Bat = Batting Runs, BsR = Baserunning Runs, Fld = Fielding Runs, "
            "Pos = Positional Adjustment, Lg = League Adjustment, "
            "Rep = Replacement Level Runs, RPW ≈ 10 Runs Per Win"
        )
    with c2:
        st.markdown(
            f"<div style='font-size:0.75rem;font-weight:600;color:{C.text_primary};margin-bottom:0.3rem;'>"
            "Pitchers (FIP-based)</div>",
            unsafe_allow_html=True,
        )
        st.latex(
            r"\text{FIP} = \frac{13 \times \text{HR} + 3 \times (\text{BB}+\text{HBP})"
            r" - 2 \times \text{K}}{\text{IP}} + C"
        )
        st.caption(
            "C = FIP constant (scales FIP to league ERA). "
            "Pitcher fWAR then converts FIP to runs above replacement level "
            "using innings pitched and a runs-per-win denominator (~10 RPW)."
        )

    # ── fWAR context: what the numbers mean ─────────────────────────────
    st.markdown(
        f"<div style='background:{C.bg_dark};border:1px solid {C.border_primary};border-radius:8px;"
        f"padding:1rem 1.2rem;margin:0.8rem 0 1.2rem;font-size:0.82rem;color:{C.text_secondary};line-height:1.8;'>"
        f"<b style='color:{C.text_primary};font-size:0.9rem;'>Understanding fWAR in Context</b><br><br>"
        "WAR estimates a player's value in terms of extra wins they provide compared to a "
        "replacement-level player — essentially a low-cost minor leaguer or bench player easily "
        "found to fill the same position. MLB Toolbox uses fWAR, a widely accepted version "
        "generated by FanGraphs.<br><br>"
        "<b style='color:#93c5fd;'>Player benchmarks (2025):</b> "
        "The average MLB player had an fWAR of <b>0.7</b>. "
        "Above-average players had an fWAR of <b>1.8+</b>. "
        "Players who make the All-Star team typically have an fWAR of <b>3.2+</b>, "
        "and MVP candidates reach <b>4.0+</b>.<br><br>"
        "<b style='color:#93c5fd;'>Team benchmarks (2025):</b> "
        "The average team fWAR was <b>33.8</b>, with the top 5 teams averaging <b>51.8</b> "
        "and the bottom 5 averaging <b>14.7</b>. "
        "Over the last 5 seasons, teams that made the playoffs had an fWAR of <b>27+</b> or higher, "
        "and World Series champions averaged <b>42.4</b>. "
        "It is very hard to build a winning team without a high fWAR."
        "</div>",
        unsafe_allow_html=True,
    )

    # ==================================================================
    # Section 2 — Our Custom Metrics
    # ==================================================================
    _section(2, "Our Custom Metrics")

    _render_glossary([
        ("W/$M", "WAR per Million Dollars",
         "Single-season efficiency ratio: WAR ÷ Salary (in $M). "
         "Higher means more production per dollar spent."),
        ("PPR", "Pay-to-Performance Ratio",
         "Career efficiency: Sum of career WAR ÷ total contract value ($M). "
         "Captures long-term value delivery across entire contract."),
        ("PPEL", "Pay-Performance Efficiency Line",
         "OLS regression of WAR ~ Salary across all players. "
         "Players below the line are underpaid (good value); above = overpaid."),
        ("PPEL3", "3-Year Weighted PPEL",
         "Weighted average WAR over 3 seasons (0.50 / 0.30 / 0.20, most recent first) "
         "regressed against current salary. Smooths single-year noise."),
        ("PPEL5", "5-Year Weighted PPEL",
         "Weighted average WAR over 5 seasons (0.35 / 0.25 / 0.20 / 0.12 / 0.08) "
         "regressed against current salary. Best for established veterans."),
        ("Residual", "Salary Residual",
         "Actual Salary − PPEL Predicted Salary (in $M). "
         "Positive = overpaid vs market; negative = underpaid (bargain)."),
        ("CEL", "Cost Effective Line",
         "Team-level equivalent of PPEL: OLS regression of total team WAR vs total team payroll. "
         "Teams below the line are spending efficiently."),
        ("Efficiency Gap", "Team Efficiency Gap",
         "Team payroll − predicted payroll for their WAR total. "
         "Negative = efficient (winning more than you're paying for)."),
        ("Est. Wins", "Estimated Wins",
         "47.7 + Roster WAR. The 47.7 baseline represents the expected wins for a team of "
         "all replacement-level players over a 162-game season."),
        ("$/WAR", "Dollars per WAR",
         "Team payroll divided by total team WAR. Shows the average cost of one win above "
         "replacement for that roster."),
        ("$/Win", "Dollars per Win (Adjusted)",
         "2026 Payroll ($M) / (Total 2025 WAR + 47.7). Unlike $/WAR, this includes the "
         "47.7 replacement-baseline wins every team gets for free. Lower = better."),
        ("WSR", "WAR Stability Rating",
         "mean WAR / (1 + std WAR) across qualifying seasons (PA ≥ 200 or IP ≥ 50). "
         "Elite ≥ 3.5, Reliable ≥ 2.0, Volatile ≥ 1.0, Unstable < 1.0. "
         "Rewards consistent production over volatile single-season peaks."),
        ("RSS", "Roster Stability Score",
         "Percentage of qualifying players (PA ≥ 150 or IP ≥ 40) who returned from "
         "the previous season. Higher RSS indicates roster continuity."),
    ], title="Custom Metrics", cols=2)

    # Formula highlights
    st.markdown(
        "<div style='margin:0.6rem 0 0.2rem;font-size:0.82rem;font-weight:700;color:#93c5fd;'>"
        "Key Formulas</div>",
        unsafe_allow_html=True,
    )

    f1, f2, f3 = st.columns(3)
    with f1:
        st.latex(r"\text{W/\$M} = \frac{\text{WAR}}{\text{Salary (\$M)}}")
    with f2:
        st.latex(r"\text{PPEL: } \hat{S} = \beta_0 + \beta_1 \times \text{WAR}")
    with f3:
        st.latex(r"\text{Est. Wins} = 47.7 + \sum \text{WAR}")

    st.caption(
        "PPEL regression is fitted via OLS across all players in the dataset. "
        "PPEL3/PPEL5 use the same approach but with time-weighted WAR inputs."
    )

    # ==================================================================
    # Section 3 — Roster & Contract Terms
    # ==================================================================
    _section(3, "Roster & Contract Terms")

    _render_glossary([
        ("CBT — Under $244M", "No Restrictions",
         "Below the Competitive Balance Tax threshold. No luxury tax penalties or restrictions."),
        ("CBT — $244M–$264M", "Tier 1 Luxury Tax",
         "First CBT tier. Team pays a 20% tax on overage (first-time) or 30% (repeat). "
         "No operational restrictions."),
        ("CBT — $264M–$284M", "1st Apron",
         "Significant restrictions: cannot receive revenue-sharing money, limited international "
         "bonus pool, pick compensation restrictions for free agent signings."),
        ("CBT — $284M–$304M", "Tier 3 / Enhanced Penalties",
         "Severe restrictions on top of 1st Apron rules. Higher tax rates, additional "
         "draft pick forfeiture, and frozen luxury tax rate escalation."),
        ("CBT — $304M+", "2nd Apron",
         "Hardest restrictions. Highest surtax rate, top draft pick drops 10 spots, "
         "cannot add salary via trade without sending equal or greater salary back."),
        ("FA", "Free Agent",
         "Player with 6+ years of MLB service time whose contract has expired. "
         "Can sign with any team on the open market."),
        ("Arb", "Arbitration-Eligible",
         "Player with 3-6 years of service time (or Super Two eligible). "
         "Salary set via negotiation or arbitration hearing if no agreement."),
        ("Pre-Arb", "Pre-Arbitration / Team Control",
         "Player with fewer than 3 years of service time. Salary near league minimum "
         "(~$740K in 2026). Team controls rights."),
        ("DFA", "Designated for Assignment",
         "Player removed from 40-man roster. Team has 7 days to trade, release, or "
         "outright the player to the minors."),
        ("Option", "Minor League Option",
         "Sending a player with options remaining to the minor leagues. A player has 3 option "
         "years; once used in a season, that year's option is burned."),
        ("NRI", "Non-Roster Invitee",
         "Player invited to Spring Training who is not on the 40-man roster. "
         "Must be added to the 40-man to make Opening Day roster."),
        ("40-Man vs 26-Man", "Roster Types",
         "40-man: players protected from Rule 5 Draft and eligible for MLB call-up. "
         "26-man: the active game-day roster (expanded to 28 in September)."),
        ("IL", "Injured List",
         "10-day IL (position players, relievers), 15-day IL (starting pitchers), "
         "and 60-day IL (long-term; player removed from 40-man count)."),
        ("Rule 5", "Rule 5 Draft Eligibility",
         "Players not on the 40-man roster after 5 years in the minors (signed at 18+) or "
         "4 years (signed at ≤18) are eligible to be drafted by other teams."),
    ], title="Roster & Contract Terms", cols=2)

    # ==================================================================
    # Section 4 — Roster Grade System
    # ==================================================================
    _section(4, "Roster Grade System")

    st.markdown(
        f"<p style='color:{C.text_muted};font-size:0.76rem;margin-bottom:0.8rem;'>"
        "Every simulated roster receives four letter grades (A+ through F) across "
        "these dimensions:</p>",
        unsafe_allow_html=True,
    )

    _render_glossary([
        ("Production", "Total WAR Output",
         "Score = Total Roster WAR ÷ 35 WAR ceiling. "
         "A+ ≥ 95%, A ≥ 85%, B ≥ 70%, C ≥ 55%, D ≥ 40%, F < 40%."),
        ("Efficiency", "WAR per Dollar",
         "Roster-wide WAR/$M compared to a 0.30 WAR/$M baseline. "
         "Higher ratio → better grade. Rewards getting production without overspending."),
        ("Depth", "Position Coverage",
         "How many of the 9 standard position groups are filled "
         "(C, 1B, 2B, 3B, SS, LF, CF, RF + SP/RP). Full coverage = A+."),
        ("Contract Health", "Years Remaining Balance",
         "Average years remaining on roster contracts vs a 2.0-year ideal. "
         "Too short (all expiring) or too long (all locked up) lowers the grade."),
    ], title="Grade Dimensions", cols=2)

    # Grade cutoff table
    st.markdown(
        "<div style='margin:0.8rem 0 0.4rem;font-size:0.82rem;font-weight:700;color:#93c5fd;'>"
        "Letter Grade Cutoffs</div>",
        unsafe_allow_html=True,
    )

    _grade_data = [
        ("A+", "≥ 95%", "Elite — best-in-class across the league"),
        ("A",  "≥ 85%", "Excellent — clear strength with minimal gaps"),
        ("B",  "≥ 70%", "Above average — solid with room to improve"),
        ("C",  "≥ 55%", "Average — meets baseline expectations"),
        ("D",  "≥ 40%", "Below average — notable weakness"),
        ("F",  "< 40%", "Poor — significant area of concern"),
    ]

    cols = st.columns(6)
    for i, (grade, pct, desc) in enumerate(_grade_data):
        with cols[i]:
            _color = {
                "A+": "#22c55e", "A": "#4ade80", "B": "#60a5fa",
                "C": "#facc15", "D": "#f97316", "F": "#ef4444",
            }[grade]
            st.markdown(
                f"<div style='text-align:center;background:{C.bg_dark};border:1px solid {C.border_primary};"
                f"border-radius:8px;padding:0.5rem 0.3rem;'>"
                f"<div style='font-size:1.3rem;font-weight:900;color:{_color};'>{grade}</div>"
                f"<div style='font-size:0.65rem;color:{C.text_muted};'>{pct}</div>"
                f"<div style='font-size:0.58rem;color:{C.text_dim};margin-top:0.2rem;'>{desc}</div>"
                f"</div>",
                unsafe_allow_html=True,
            )

    # Example comparison
    st.markdown(
        "<div style='margin:0.8rem 0 0.4rem;font-size:0.82rem;font-weight:700;color:#93c5fd;'>"
        "Example: A+ Roster vs C Roster</div>",
        unsafe_allow_html=True,
    )

    ex1, ex2 = st.columns(2)
    with ex1:
        st.markdown(
            f"<div style='background:{C.bg_dark};border:1px solid #22c55e;border-radius:8px;"
            f"padding:0.6rem 0.8rem;'>"
            f"<div style='font-size:0.8rem;font-weight:700;color:#22c55e;margin-bottom:0.3rem;'>"
            f"A+ Roster Example</div>"
            f"<div style='font-size:0.75rem;color:{C.text_secondary};line-height:1.7;'>"
            f"<b style='color:{C.text_primary};'>Production:</b> ~33+ WAR (≥95% of 35 ceiling)<br>"
            f"<b style='color:{C.text_primary};'>Efficiency:</b> WAR/$M well above 0.30 baseline<br>"
            f"<b style='color:{C.text_primary};'>Depth:</b> All 9 position groups filled<br>"
            f"<b style='color:{C.text_primary};'>Contract Health:</b> ~2.0 avg years remaining"
            f"</div></div>",
            unsafe_allow_html=True,
        )
    with ex2:
        st.markdown(
            f"<div style='background:{C.bg_dark};border:1px solid #facc15;border-radius:8px;"
            f"padding:0.6rem 0.8rem;'>"
            f"<div style='font-size:0.8rem;font-weight:700;color:#facc15;margin-bottom:0.3rem;'>"
            f"C Roster Example</div>"
            f"<div style='font-size:0.75rem;color:{C.text_secondary};line-height:1.7;'>"
            f"<b style='color:{C.text_primary};'>Production:</b> ~19-20 WAR (55-60% of ceiling)<br>"
            f"<b style='color:{C.text_primary};'>Efficiency:</b> WAR/$M near or below 0.30<br>"
            f"<b style='color:{C.text_primary};'>Depth:</b> 5-6 of 9 groups filled, gaps at key spots<br>"
            f"<b style='color:{C.text_primary};'>Contract Health:</b> Skewed toward all expiring or all long-term"
            f"</div></div>",
            unsafe_allow_html=True,
        )

    # ==================================================================
    # Section 5 — Data Sources & Methodology
    # ==================================================================
    _section(5, "Data Sources & Methodology")

    st.markdown(
        f"<div style='background:{C.bg_dark};border:1px solid {C.border_primary};border-radius:8px;"
        f"padding:1rem 1.2rem;font-size:0.76rem;color:{C.text_muted};line-height:1.8;'>"
        f"<b style='color:{C.text_primary};font-size:0.82rem;'>Where the data comes from</b><br><br>"
        "<b style='color:#93c5fd;'>WAR & Performance Data:</b> "
        "All WAR figures use FanGraphs fWAR, covering the 2021–2025 MLB seasons. "
        "Pitchers are evaluated via FIP-based WAR; position players use the full "
        "batting + baserunning + fielding + positional framework.<br><br>"
        "<b style='color:#93c5fd;'>Salary & Payroll Data:</b> "
        "2026 contract commitments sourced per-team from publicly available payroll reports. "
        "Includes base salary, signing bonuses, and incentives where applicable.<br><br>"
        "<b style='color:#93c5fd;'>40-Man Rosters:</b> "
        "Current 40-man roster composition is pulled from the MLB Stats API "
        "(statsapi.mlb.com) and updated periodically.<br><br>"
        "<b style='color:#93c5fd;'>Projection Approach:</b> "
        "All analysis is backward-looking — we use historical WAR to evaluate efficiency, "
        "not forward-looking projection systems (ZiPS, Steamer, etc.). "
        "This means the metrics reflect what players <i>have</i> done, not what they "
        "are projected to do.<br><br>"
        "<b style='color:#93c5fd;'>Research Context:</b> "
        "MLB Toolbox is a university research project. It is not financial advice, "
        "not affiliated with MLB or any franchise, and should not be used for "
        "gambling or professional roster decisions.<br><br>"
        "<b style='color:#93c5fd;'>Last Updated:</b> "
        "Data covers through the 2025 MLB season."
        "</div>",
        unsafe_allow_html=True,
    )

    _render_feedback_widget("glossary")
